kafka:
  trustStoreLocation: ""
  bootstrapServers: 127.0.0.1:9092
  groupId: "consumer-group-tax-payer"
  acksConfig: "all"
  retriesConfig: 10
  autoOffsetReset: "earliest"

  topic:
    numPartitions: 3
    replicationFactor: 1

logging:
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'