kafka:
  trustStoreLocation: ""
  bootstrapServers: 127.0.0.1:9092

  topic:
    taxpayer:
      name: "com.example.taxpayer.0"
      acksConfig: "all"
      retriesConfig: 10
      groupId: "consumer-group-tax-payer"
      autoOffsetReset: "earliest"
      retention: "-1"
      partitionCount: 3
      replicaCount: 1